name: Build and Test

on:
  pull_request:
    branches: [ "*" ]
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install docker
        uses: KengoTODA/actions-setup-docker-compose@main
        with:
          version: '1.29.2'
      - name: Install make
        run: sudo apt-get install -y make
          
      - name: Build and tag
        run: make build
        
      - name: Run unit tests
        run: make run_unit_tests
        
      - name: Upload unit tests artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: app/test-report
        if: ${{ always() }}
        
      - name: Run functional tests
        run: make run_functional_tests
        
      - name: Upload functional tests artifact
        uses: actions/upload-artifact@v3
        with:
          name: behavioral-test-results
          path: app/behavioral-test-results
        if: ${{ always() }}
        